apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: ai-loan-pod
  name: ai-loan-pod
spec:
  selector:
    matchLabels:
      run: ai-loan-pod
  template:
    metadata:
      labels:
        run: ai-loan-pod
    spec:
      containers:
      - image: registry.git.chalmers.se/courses/dit826/2023/group6/ailoan:latest
        name: ai-loan-pod
      imagePullSecrets:
      - name: app-secret
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: loan-app-svc
  name: loan-app-svc
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: ai-loan-pod
    app: loan-app-svc
  type: NodePort
status:
  loadBalancer: {}
