# Generated by Django 5.0 on 2023-12-23 01:10

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loanApp", "0021_alter_loanapplicant_loanid"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewLoanApplicant",
            fields=[
                (
                    "LoanID",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("Age", models.IntegerField()),
                ("Income", models.FloatField()),
                ("LoanAmount", models.FloatField()),
                ("CreditScore", models.IntegerField()),
                ("MonthsEmployed", models.IntegerField()),
                ("LoanTerm", models.IntegerField()),
                ("DTIRatio", models.FloatField()),
                ("Default", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("reviewed", "Reviewed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Applicant",
        ),
        migrations.AlterField(
            model_name="loanapplicant",
            name="LoanID",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                max_length=12,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
