# Generated by Django 5.0 on 2023-12-31 00:31

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loanApp", "0023_delete_savedmodel_alter_loanapplicant_loanid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplicant",
            name="LoanID",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                max_length=12,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="newloanapplicant",
            name="LoanID",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                max_length=12,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
